using FulfillmentHub.Domain.Common;
using FulfillmentHub.Domain.Customers;
using FulfillmentHub.Domain.Deliveries;
using FulfillmentHub.Domain.Identity;
using FulfillmentHub.Domain.Orders.Events;
using FulfillmentHub.Domain.Payments;

namespace FulfillmentHub.Domain.Orders;

/// <summary>
/// The order aggregate: items with price snapshots, delivery address snapshot, totals and the status state machine
/// documented in docs/DOMAIN.md §5. Stock reservation and provider calls happen outside (use cases / handlers);
/// the aggregate only guarantees its own invariants and records what happened.
/// </summary>
public sealed class Order : AggregateRoot<OrderId>
{
    public const int MaxItems = 50;
    public const int IdempotencyKeyMaxLength = 64;

    private static readonly Dictionary<OrderStatus, OrderStatus[]> AllowedTransitions =
        new Dictionary<OrderStatus, OrderStatus[]>
        {
            [OrderStatus.Created] = [OrderStatus.AwaitingPayment, OrderStatus.Cancelled],
            [OrderStatus.AwaitingPayment] = [OrderStatus.Paid, OrderStatus.Cancelled],
            [OrderStatus.Paid] = [OrderStatus.DeliveryRequested, OrderStatus.Cancelled],
            [OrderStatus.DeliveryRequested] = [OrderStatus.InDelivery, OrderStatus.Cancelled],
            [OrderStatus.InDelivery] = [OrderStatus.Delivered, OrderStatus.Cancelled],
            [OrderStatus.Delivered] = [],
            [OrderStatus.Cancelled] = [],
        };

    private readonly List<OrderItem> _items = [];
    private readonly List<OrderStatusChange> _statusHistory = [];

    private Order(OrderId id)
        : base(id)
    {
    }

    /// <summary>Human-readable sequential number, generated by the database on insert.</summary>
    public long Number { get; private set; }

    public CustomerId CustomerId { get; private set; }

    public Address DeliveryAddress { get; private set; } = null!;

    public Money Subtotal { get; private set; } = null!;

    public Money? DeliveryFee { get; private set; }

    public Money Total { get; private set; } = null!;

    public OrderStatus Status { get; private set; }

    public OrderCancellationReason? CancellationReason { get; private set; }

    public PaymentId? PaymentId { get; private set; }

    public DeliveryId? DeliveryId { get; private set; }

    public string? IdempotencyKey { get; private set; }

    public DateTimeOffset CreatedAt { get; private set; }

    public DateTimeOffset UpdatedAt { get; private set; }

    public IReadOnlyList<OrderItem> Items => _items.AsReadOnly();

    /// <summary>Chronological. Rows come back from the database in no guaranteed order, so the aggregate sorts.</summary>
    public IReadOnlyList<OrderStatusChange> StatusHistory => _statusHistory.OrderBy(h => h.At).ToList();

    public bool IsFinal => Status is OrderStatus.Delivered or OrderStatus.Cancelled;

    public static Order Place(
        Customer customer,
        Address deliveryAddress,
        IReadOnlyCollection<OrderLine> lines,
        string? idempotencyKey,
        DateTimeOffset now)
    {
        if (!customer.IsActive)
        {
            throw new DomainException($"Customer '{customer.Id}' is inactive and cannot place orders.");
        }

        if (lines.Count is 0 or > MaxItems)
        {
            throw new DomainException($"An order must have between 1 and {MaxItems} items.");
        }

        if (lines.Select(l => l.Product.Id).Distinct().Count() != lines.Count)
        {
            throw new DomainException("An order cannot contain the same product more than once.");
        }

        if (idempotencyKey is { Length: > IdempotencyKeyMaxLength })
        {
            throw new DomainException($"Idempotency key must have at most {IdempotencyKeyMaxLength} characters.");
        }

        var order = new Order(OrderId.New())
        {
            CustomerId = customer.Id,
            DeliveryAddress = deliveryAddress,
            Status = OrderStatus.Created,
            IdempotencyKey = idempotencyKey,
            CreatedAt = now,
            UpdatedAt = now,
        };

        foreach (var line in lines)
        {
            order._items.Add(OrderItem.Create(line.Product, line.Quantity));
        }

        order.Subtotal = order._items.Aggregate(Money.Zero(order._items[0].UnitPrice.Currency), (sum, item) => sum + item.LineTotal);
        order.Total = order.Subtotal;
        order._statusHistory.Add(OrderStatusChange.Create(OrderStatus.Created, OrderStatus.Created, now, "Order placed", null));
        order.Raise(new OrderPlaced(order.Id, order.CustomerId, order.Total, now));

        return order;
    }

    /// <summary>
    /// Freezes the delivery fee charged to the customer, quoted at checkout (D-51). Only before payment: the amount
    /// charged must include it. What the provider actually costs later lives on the <c>Delivery</c>.
    /// </summary>
    public void SetDeliveryFee(Money deliveryFee, DateTimeOffset now)
    {
        if (Status != OrderStatus.Created)
        {
            throw new DomainException($"Delivery fee can only be set before payment (status is '{Status}').");
        }

        if (deliveryFee.IsNegative)
        {
            throw new DomainException("Delivery fee cannot be negative.");
        }

        DeliveryFee = deliveryFee;
        Total = Subtotal + deliveryFee;
        UpdatedAt = now;
    }

    /// <summary>A payment was created at the provider; the order now waits for its confirmation.</summary>
    public void MarkAwaitingPayment(PaymentId paymentId, DateTimeOffset now)
    {
        if (Status == OrderStatus.AwaitingPayment && PaymentId == paymentId)
        {
            return;
        }

        Transition(OrderStatus.AwaitingPayment, now, reason: null, actor: null);
        PaymentId = paymentId;
    }

    public void MarkAsPaid(PaymentId paymentId, DateTimeOffset now)
    {
        if (Status == OrderStatus.Paid)
        {
            return;
        }

        Transition(OrderStatus.Paid, now, reason: null, actor: null);
        PaymentId = paymentId;
        Raise(new OrderPaid(Id, paymentId, now));
    }

    public void MarkDeliveryRequested(DeliveryId deliveryId, Money deliveryFee, DateTimeOffset now)
    {
        if (Status == OrderStatus.DeliveryRequested && DeliveryId == deliveryId)
        {
            return;
        }

        if (deliveryFee.IsNegative)
        {
            throw new DomainException("Delivery fee cannot be negative.");
        }

        Transition(OrderStatus.DeliveryRequested, now, reason: null, actor: null);
        DeliveryId = deliveryId;
        DeliveryFee = deliveryFee;
        Total = Subtotal + deliveryFee;
        Raise(new OrderDeliveryRequested(Id, deliveryId, now));
    }

    public void MarkInDelivery(DateTimeOffset now)
    {
        if (Status == OrderStatus.InDelivery)
        {
            return;
        }

        Transition(OrderStatus.InDelivery, now, reason: null, actor: null);
    }

    public void MarkDelivered(DateTimeOffset now)
    {
        if (Status == OrderStatus.Delivered)
        {
            return;
        }

        Transition(OrderStatus.Delivered, now, reason: null, actor: null);
        Raise(new OrderDelivered(Id, now));
    }

    /// <summary>
    /// Cancels the order. Which reasons are acceptable depends on the current status (see docs/DOMAIN.md §5):
    /// customers cannot cancel once the courier has the parcel; payment reasons only apply before payment, etc.
    /// </summary>
    public void Cancel(OrderCancellationReason reason, DateTimeOffset now, UserId? actor = null, string? note = null)
    {
        if (Status == OrderStatus.Cancelled)
        {
            return;
        }

        if (!IsCancellationAllowed(Status, reason))
        {
            throw new DomainException($"Order in status '{Status}' cannot be cancelled with reason '{reason}'.");
        }

        var previous = Status;
        Transition(OrderStatus.Cancelled, now, note ?? reason.ToString(), actor);
        CancellationReason = reason;
        Raise(new OrderCancelled(Id, reason, previous, now));
    }

    /// <summary>Whether <see cref="Cancel"/> would succeed from the current status with the given reason.</summary>
    public bool CanCancel(OrderCancellationReason reason) => Status == OrderStatus.Cancelled || IsCancellationAllowed(Status, reason);

    private static bool IsCancellationAllowed(OrderStatus status, OrderCancellationReason reason) => reason switch
    {
        OrderCancellationReason.CustomerRequest =>
            status is OrderStatus.Created or OrderStatus.AwaitingPayment or OrderStatus.Paid or OrderStatus.DeliveryRequested,
        OrderCancellationReason.PaymentFailed or OrderCancellationReason.PaymentTimeout =>
            status is OrderStatus.Created or OrderStatus.AwaitingPayment,
        OrderCancellationReason.StockUnavailable => status is OrderStatus.Created,
        OrderCancellationReason.DeliveryFailed =>
            status is OrderStatus.Paid or OrderStatus.DeliveryRequested or OrderStatus.InDelivery,
        OrderCancellationReason.OperatorAction => status is not (OrderStatus.Delivered or OrderStatus.Cancelled),
        _ => false,
    };

    private void Transition(OrderStatus to, DateTimeOffset now, string? reason, UserId? actor)
    {
        if (!AllowedTransitions[Status].Contains(to))
        {
            throw new InvalidStateTransitionException(nameof(Order), Status.ToString(), to.ToString());
        }

        _statusHistory.Add(OrderStatusChange.Create(Status, to, now, reason, actor));
        Status = to;
        UpdatedAt = now;
    }
}
